# Generated by Django 3.2.4 on 2021-09-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='photos')),
                ('country', models.CharField(blank=True, choices=[('France', 'France'), ('England', 'England'), ('Japan', 'Japan')], max_length=50, null=True)),
                ('type', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField()),
                ('dishes', models.ManyToManyField(blank=True, null=True, to='restaurant_sys.dish')),
            ],
        ),
        migrations.CreateModel(
            name='bill_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_sys.dish')),
            ],
        ),
    ]
