# Generated by Django 3.2.4 on 2021-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('cus_phone', models.CharField(max_length=12)),
                ('bill_item', models.ManyToManyField(blank=True, null=True, to='restaurant_sys.bill_item')),
            ],
        ),
    ]
