# Generated by Django 3.2.4 on 2021-09-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sys', '0002_bill_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_order',
            name='total_price',
        ),
    ]
