# Generated by Django 3.2.4 on 2021-09-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sys', '0004_alter_bill_order_cus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_item',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='restaurant_sys.dish'),
        ),
    ]
