# Generated by Django 3.2.4 on 2021-09-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sys', '0005_alter_bill_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_order',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
