# Generated by Django 3.2.4 on 2021-09-24 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sys', '0006_bill_order_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_order',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
